### ISSUE TITLE
JAR file for Mod the Spire 3.6.3?

### ISSUE THREAD

**Issue by AvangionQ** [jhp109/TheCursedMod#1]
How can I play this on Mod the Spire 3.6.3 without a JAR file? Want to try this out ...

**Comment by jhp109** [comment]
I'm not sure what is your intention, so I can advise followings :
- If you just want to play this mod, try visit steam workshop, find "The Cursed", and subscribe it.
- If you want to build this repository with MtS 3.6.3, try changing mts_version in ModTheSpire.json from 3.8.3 to 3.6.3 and build (not sure if it will work though).

**Comment by AvangionQ** [comment]
> I'm not sure what is your intention, 

To play The Cursed Mod using ... https://github.com/kiooeht/ModTheSpire/releases/tag/v3.6.3

**Comment by jhp109** [comment]
This mod is based on MtS v3.8.3 like I said.
Also I don't have a plan to release my mod's jar file here, as it's already available in Steam workshop. Sorry.
