### ISSUE TITLE
Text bug in Mana Circulation tooltip

### ISSUE THREAD

**Issue by Bloodrocution** [jhp109/TheCursedMod#6]
Should be the icon for energy, but it shows "[E]" instead:
![Mana Circulation](https://puu.sh/GS07Y/2037738702.png)

It displays correctly elsewhere; for example:
![Energy](https://puu.sh/GS0cv/718b3b96c1.png)
----------------------------------------------------------------

Here's my most list and whatnot. Nothing that should conflict.

Mod list:
![STS version](https://puu.sh/GS0aX/591dc997d8.png)
![Mod list](https://puu.sh/GS0af/2b5113168f.png)

**Comment by jhp109** [comment]
Sorry for the late response. Fixed by https://github.com/jhp109/TheCursedMod/commit/b19b8bc38ce35875ff8b78537ebf7f698f14ff1e
